**Practice 1: Train Softmax Regression for multi-class classifiation**

---



In [1]:
# practice 1.1: setup iris dataset for multi-class classification
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()

# get features from iris data
X = iris["data"][:, :] # using all features

# keep all labels for multi-class classification
y = iris["target"]

print(X.shape)
print(y)

(150, 4)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [2]:
# practice 1.2: Train the Softmax Regression classifier
from sklearn.linear_model import LogisticRegression
softmax_regression = LogisticRegression(multi_class='multinomial', solver='lbfgs')
softmax_regression.fit(X, y)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(multi_class='multinomial')

In [3]:
# practice 1.3: get the predicted labels for training instances
y_prediction_labels = softmax_regression.predict(X)

In [4]:
# practice 1.4: get the predicted probabilities of both classes for training instances
y_prediction_probs = softmax_regression.predict_proba(X)
y_prediction_probs 

array([[9.81801790e-01, 1.81981959e-02, 1.43556907e-08],
       [9.71727348e-01, 2.82726221e-02, 3.00307256e-08],
       [9.85451821e-01, 1.45481667e-02, 1.22669829e-08],
       [9.76299555e-01, 2.37004051e-02, 3.95392775e-08],
       [9.85388794e-01, 1.46111946e-02, 1.18844386e-08],
       [9.70470231e-01, 2.95296954e-02, 7.31658657e-08],
       [9.86892099e-01, 1.31078812e-02, 1.98813481e-08],
       [9.76403999e-01, 2.35959736e-02, 2.74987214e-08],
       [9.79846470e-01, 2.01534997e-02, 3.05483138e-08],
       [9.69136281e-01, 3.08636877e-02, 3.15045384e-08],
       [9.76507990e-01, 2.34919910e-02, 1.91247633e-08],
       [9.75414682e-01, 2.45852747e-02, 4.36441157e-08],
       [9.74561901e-01, 2.54380777e-02, 2.13874589e-08],
       [9.91974148e-01, 8.02584827e-03, 3.87570298e-09],
       [9.88203900e-01, 1.17960975e-02, 2.79268763e-09],
       [9.86776508e-01, 1.32234792e-02, 1.27205635e-08],
       [9.88117663e-01, 1.18823279e-02, 9.15150624e-09],
       [9.81557981e-01, 1.84419

In [5]:
from sklearn.metrics import accuracy_score
#accuracy_score(y_true, y_pred)
accuracy_score(y, y_prediction_labels)

0.9733333333333334

**Practice 2: Build multi-layer neural network for binary classification**

---



In [6]:
# practice 2.1: Load training data
import pandas as pd
from sklearn.utils import shuffle
train_data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/spect/SPECT.train', header=None)
train_data.columns = ['Label']+[ 'F'+str(i) for i in range(1,23)]
train_data = shuffle(train_data) # shuffle data
train_data

Label  F1  F2  F3  F4  F5  F6  F7  F8  F9  ...  F13  F14  F15  F16  F17  \
31      1   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
45      0   1   0   0   0   1   0   0   0   0  ...    0    0    0    0    0   
32      1   1   1   0   0   1   1   1   0   0  ...    0    0    0    0    1   
56      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
16      1   0   0   1   1   0   0   0   1   1  ...    1    1    0    1    0   
..    ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
76      0   1   0   0   0   1   1   0   0   1  ...    0    1    0    0    0   
17      1   0   0   0   0   0   0   1   0   0  ...    0    0    0    0    0   
71      0   0   0   0   0   0   1   0   0   0  ...    0    0    0    0    0   
12      1   1   0   0   0   1   0   0   0   0  ...    1    0    0    0    0   
0       1   0   0   0   1   0   0   0   1   1  ...    1    1    0    0    0   

    F18  F19  F20  F21  F22  
31    0    0    0    0    0  
45    0    0    0    0    1  
32    0    1    0    0    1  
56    0    1    1    0    0  
16    0    0    0    1    0  
..  ...  ...  ...  ...  ...  
76    0    1    1    0    0  
17    0    0    0    0    1  
71    0    0    0    0    0  
12    0    0    0    1    1  
0     0    0    0    0    0  

[80 rows x 23 columns]

In [7]:
# practice 2.2: Load testing data
import pandas as pd
test_data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/spect/SPECT.test', header=None)
test_data.columns = ['Label']+[ 'F'+str(i) for i in range(1,23)]
test_data

Label  F1  F2  F3  F4  F5  F6  F7  F8  F9  ...  F13  F14  F15  F16  F17  \
0        1   1   0   0   1   1   0   0   0   1  ...    0    1    1    1    0   
1        1   1   0   0   1   1   0   0   0   0  ...    1    0    0    0    0   
2        1   0   0   0   1   0   1   0   0   1  ...    0    1    1    0    0   
3        1   0   1   1   1   0   0   1   0   1  ...    1    1    0    1    0   
4        1   0   0   1   0   0   0   0   1   0  ...    1    1    0    1    0   
..     ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
182      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
183      0   1   1   0   0   0   1   0   0   0  ...    0    0    0    1    0   
184      0   1   0   1   0   1   0   0   1   0  ...    1    0    1    1    0   
185      0   1   0   1   0   1   0   0   1   1  ...    0    1    0    1    0   
186      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   

     F18  F19  F20  F21  F22  
0      0    1    1    0    0  
1      0    0    0    0    0  
2      0    0    0    0    1  
3      0    0    0    1    0  
4      0    0    0    0    1  
..   ...  ...  ...  ...  ...  
182    0    0    0    0    0  
183    0    0    0    0    0  
184    0    0    0    0    0  
185    0    0    0    0    0  
186    0    0    0    0    0  

[187 rows x 23 columns]

In [8]:
# practice 2.3: import Sequential class and Dense class from keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [9]:
# practice 2.4: build a three-layer neural network with binary function as output
model = Sequential()
model.add(Dense(100, activation="relu", input_shape=(22,))) # input layer1 --> hidden layer1
model.add(Dense(100, activation="relu")) # hidden layer 1 --> hidden layer 2
model.add(Dense(1, activation="sigmoid")) # hidden layer 2 --> output layer 
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 100)               2300      
                                                                 
 dense_1 (Dense)             (None, 100)               10100     
                                                                 
 dense_2 (Dense)             (None, 1)                 101       
                                                                 
Total params: 12,501
Trainable params: 12,501
Non-trainable params: 0
_________________________________________________________________


**Practice 3: Define the first hidden layer in model architecture**

---



In [10]:
## Practice 3.1: extract features and labels from the training/test data
train_label = train_data['Label']
train_features = train_data.drop('Label',axis= 1)
print("train_features.shape:",train_features.shape)

test_label = test_data['Label']
test_features = test_data.drop('Label',axis=1)
print("test_features.shape:",test_features.shape)

train_features.shape: (80, 22)
test_features.shape: (187, 22)


In [45]:
test_label

0      1
1      1
2      1
3      1
4      1
      ..
182    0
183    0
184    0
185    0
186    0
Name: Label, Length: 187, dtype: int64

In [11]:
## Practice 3.2: Define the first hidden layer in model architecture
from keras.models import Sequential
from keras.layers import Dense
model = Sequential() # initialize Sequential model

# add connection layers into sequential model
model.add(Dense(100, input_shape=(22,),activation='relu')) # input layer -> hidden layer 1

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 100)               2300      
                                                                 
Total params: 2,300
Trainable params: 2,300
Non-trainable params: 0
_________________________________________________________________


**Practice 4: Add more hidden layers and output layers into network**

---



In [12]:
## Practice 4: Add more hidden layers and output layers into network
from keras.models import Sequential
from keras.layers import Dense

model = Sequential() # initialize Sequential model
model.add(Dense(100, input_shape=(22,), activation='relu')) # input layer -> hidden layer 1
model.add(Dense(100, activation='relu')) # hidden layer 1 -> hidden layer 2
model.add(Dense(1, activation='sigmoid')) # hidden layer 2 -> output layer
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 100)               2300      
                                                                 
 dense_5 (Dense)             (None, 100)               10100     
                                                                 
 dense_6 (Dense)             (None, 1)                 101       
                                                                 
Total params: 12,501
Trainable params: 12,501
Non-trainable params: 0
_________________________________________________________________


**Practice 5: Compile the model for backpropagation, and start training model on data**

---



https://www.simplilearn.com/tutorials/machine-learning-tutorial/what-is-epoch-in-machine-learning#:~:text=An%20epoch%20is%20when%20all,dataset%20takes%20around%20an%20algorithm.

In [13]:
## Practice 5.1: Compile the model for backpropagation, and start training model on data
from keras.models import Sequential
from keras.layers import Dense

model = Sequential() # initialize Sequential model
model.add(Dense(100, input_shape=(22,), activation='relu')) # input layer -> hidden layer 1
model.add(Dense(100, activation='relu')) # hidden layer 1 -> hidden layer 2
model.add(Dense(1, activation='sigmoid')) # hidden layer 2 -> output layer

# Compile model, use binary crossentropy, and stochastic gradient descent for optimization
model.compile(loss='binary_crossentropy', optimizer='SGD', metrics=['accuracy'])

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_7 (Dense)             (None, 100)               2300      
                                                                 
 dense_8 (Dense)             (None, 100)               10100     
                                                                 
 dense_9 (Dense)             (None, 1)                 101       
                                                                 
Total params: 12,501
Trainable params: 12,501
Non-trainable params: 0
_________________________________________________________________


In [14]:
## Practice 5.2: start training the model on the features and labels, set the training epochs to 10 
model.fit(train_features, train_label, epochs = 10)

Epoch 1/10
3/3 [==============================] - 2s 11ms/step - loss: 0.7153 - accuracy: 0.4250
Epoch 2/10
3/3 [==============================] - 0s 5ms/step - loss: 0.7098 - accuracy: 0.4250
Epoch 3/10
3/3 [==============================] - 0s 16ms/step - loss: 0.7051 - accuracy: 0.4250
Epoch 4/10
3/3 [==============================] - 0s 6ms/step - loss: 0.7009 - accuracy: 0.5000
Epoch 5/10
3/3 [==============================] - 0s 8ms/step - loss: 0.6968 - accuracy: 0.5625
Epoch 6/10
3/3 [==============================] - 0s 21ms/step - loss: 0.6917 - accuracy: 0.5375
Epoch 7/10
3/3 [==============================] - 0s 12ms/step - loss: 0.6871 - accuracy: 0.4875
Epoch 8/10
3/3 [==============================] - 0s 16ms/step - loss: 0.6836 - accuracy: 0.6500
Epoch 9/10
3/3 [==============================] - 0s 6ms/step - loss: 0.6799 - accuracy: 0.5875
Epoch 10/10
3/3 [==============================] - 0s 16ms/step - loss: 0.6767 - accuracy: 0.6875


**Practice 6: Evaluate the neural network**

---



In [15]:
## practice 6.1: save the model to local disk, or load the model for predictions
from tensorflow.keras.models import load_model
model.save("SPECT.h5")
model_loaded = load_model("SPECT.h5")

In [16]:
## practice 6.2: evaluate the model performance using evaluate() method
model_loaded.evaluate(train_features, train_label)

3/3 [==============================] - 0s 8ms/step - loss: 0.6738 - accuracy: 0.7000


[0.6737866401672363, 0.699999988079071]

In [17]:
## practice 6.3: make a prediction on training set and test set
train_predictions = model_loaded.predict(train_features)
test_predictions = model_loaded.predict(test_features)
print("train_predictions: ",train_predictions) # the prediction is the probability of the class

6/6 [==============================] - 0s 5ms/step
train_predictions:  [[0.4990081 ]
 [0.5093839 ]
 [0.5213063 ]
 [0.4797928 ]
 [0.47924677]
 [0.487916  ]
 [0.52186584]
 [0.54764736]
 [0.5126055 ]
 [0.4990081 ]
 [0.5248227 ]
 [0.4990081 ]
 [0.46865463]
 [0.56693107]
 [0.5624897 ]
 [0.4892174 ]
 [0.4990081 ]
 [0.44666338]
 [0.572453  ]
 [0.4990081 ]
 [0.4990081 ]
 [0.4990081 ]
 [0.487916  ]
 [0.524132  ]
 [0.5715549 ]
 [0.52186584]
 [0.5266548 ]
 [0.48797998]
 [0.52186584]
 [0.5333763 ]
 [0.48829693]
 [0.5267415 ]
 [0.52467644]
 [0.46948692]
 [0.4990081 ]
 [0.47461516]
 [0.5257888 ]
 [0.4990081 ]
 [0.54691434]
 [0.48797998]
 [0.5245832 ]
 [0.47530046]
 [0.4919218 ]
 [0.5561162 ]
 [0.5235548 ]
 [0.5080599 ]
 [0.52169794]
 [0.4990081 ]
 [0.4674453 ]
 [0.57388514]
 [0.5255627 ]
 [0.5070503 ]
 [0.4990081 ]
 [0.52186584]
 [0.4990081 ]
 [0.55711824]
 [0.47910923]
 [0.48844764]
 [0.4990081 ]
 [0.50713575]
 [0.5229863 ]
 [0.5362233 ]
 [0.51089704]
 [0.46329138]
 [0.5365682 ]
 [0.52640903]
 [0.5

In [18]:
## practice 6.4: convert probability to labels
import numpy as np
train_prediction_labels = (train_predictions > 0.5).astype(int)
test_prediction_labels = (test_predictions > 0.5).astype(int)

In [19]:
## practice 6.5: convert probability to labels
from sklearn.metrics import accuracy_score
print("Training accuracy: ", accuracy_score(train_label, train_prediction_labels))
print("Test accuracy: ", accuracy_score(test_label, test_prediction_labels))

Training accuracy:  0.7
Test accuracy:  0.6844919786096256


In [20]:
from sklearn.metrics import f1_score
print("Training f1_score: ", f1_score(train_label, train_prediction_labels))
print("Test f1_score: ", f1_score(test_label, test_prediction_labels))

from sklearn.metrics import recall_score
print("Training recall_score: ", recall_score(train_label, train_prediction_labels))
print("Test recall_score: ", recall_score(test_label, test_prediction_labels))

from sklearn.metrics import precision_score
print("Training precision_score: ", precision_score(train_label, train_prediction_labels))
print("Test precision_score: ", precision_score(test_label, test_prediction_labels))

Training f1_score:  0.7142857142857143
Test f1_score:  0.7972508591065293
Training recall_score:  0.75
Test recall_score:  0.6744186046511628
Training precision_score:  0.6818181818181818
Test precision_score:  0.9747899159663865


**Practice 7: Monitor the model performance using validation set**

---



In [21]:
# Practice 7.1: Monitor the model performance using validation set
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(train_features, train_label, test_size=0.2, random_state=42)

## option 1: monitor the model training using validation data
model.fit(X_train, y_train, validation_data= (X_val, y_val), epochs = 20)

Epoch 1/20
2/2 [==============================] - 1s 440ms/step - loss: 0.6710 - accuracy: 0.7344 - val_loss: 0.6822 - val_accuracy: 0.5625
Epoch 2/20
2/2 [==============================] - 0s 102ms/step - loss: 0.6681 - accuracy: 0.7344 - val_loss: 0.6813 - val_accuracy: 0.5625
Epoch 3/20
2/2 [==============================] - 0s 121ms/step - loss: 0.6656 - accuracy: 0.7344 - val_loss: 0.6804 - val_accuracy: 0.5625
Epoch 4/20
2/2 [==============================] - 0s 49ms/step - loss: 0.6630 - accuracy: 0.7344 - val_loss: 0.6796 - val_accuracy: 0.5625
Epoch 5/20
2/2 [==============================] - 0s 67ms/step - loss: 0.6608 - accuracy: 0.7500 - val_loss: 0.6788 - val_accuracy: 0.6250
Epoch 6/20
2/2 [==============================] - 0s 108ms/step - loss: 0.6582 - accuracy: 0.7500 - val_loss: 0.6781 - val_accuracy: 0.5625
Epoch 7/20
2/2 [==============================] - 0s 95ms/step - loss: 0.6559 - accuracy: 0.7500 - val_loss: 0.6774 - val_accuracy: 0.5625
Epoch 8/20
2/2 [=======

In [22]:
## option 2: monitor the model training using validation data
model.fit(X_train, y_train, validation_split=0.2, epochs = 20)

Epoch 1/20
2/2 [==============================] - 1s 515ms/step - loss: 0.6320 - accuracy: 0.7059 - val_loss: 0.6145 - val_accuracy: 0.7692
Epoch 2/20
2/2 [==============================] - 0s 220ms/step - loss: 0.6303 - accuracy: 0.7059 - val_loss: 0.6128 - val_accuracy: 0.7692
Epoch 3/20
2/2 [==============================] - 0s 95ms/step - loss: 0.6291 - accuracy: 0.6863 - val_loss: 0.6113 - val_accuracy: 0.7692
Epoch 4/20
2/2 [==============================] - 0s 115ms/step - loss: 0.6275 - accuracy: 0.7059 - val_loss: 0.6097 - val_accuracy: 0.7692
Epoch 5/20
2/2 [==============================] - 0s 146ms/step - loss: 0.6260 - accuracy: 0.7255 - val_loss: 0.6079 - val_accuracy: 0.7692
Epoch 6/20
2/2 [==============================] - 0s 102ms/step - loss: 0.6245 - accuracy: 0.6863 - val_loss: 0.6062 - val_accuracy: 0.7692
Epoch 7/20
2/2 [==============================] - 0s 48ms/step - loss: 0.6231 - accuracy: 0.6863 - val_loss: 0.6044 - val_accuracy: 0.7692
Epoch 8/20
2/2 [======

**Tuning Parameters in Keras**

---



In [23]:
data_label = train_data["Label"]
data_feature = train_data.drop("Label",axis=1)

In [24]:
from keras import optimizers
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
from sklearn import metrics
from sklearn.model_selection import train_test_split


def build_model():
  model = Sequential()
  model.add(Dense(100,activation="relu"))
  model.add(Dense(100,activation="relu"))
  model.add(Dense(1,activation="sigmoid"))
  return model

X_train, X_val, y_train, y_cal = train_test_split(data_feature, data_label, test_size=0.2, random_state=42)
learning_rate_options = [0.001, 0.01, 0.1]
for learning_rate in learning_rate_options:
  model = build_model()
  optimizer_to_run = SGD(learning_rate=learning_rate)
  model.compile(loss="binary_crossentropy", optimizer=optimizer_to_run, metrics=["accuracy"])
  model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs= 100, verbose=None)
  model.save("model_lr"+str(learning_rate)+".h5")
  print("Learning rate: ", learning_rate, "Validation Accuracy:", model.evaluate(X_val, y_val, verbose=None))

Learning rate:  0.001 Validation Accuracy: [0.6793439388275146, 0.5625]
Learning rate:  0.01 Validation Accuracy: [0.6957374811172485, 0.5625]
Learning rate:  0.1 Validation Accuracy: [1.198738694190979, 0.625]


In [25]:
from keras import optimizers
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
from sklearn import metrics
from sklearn.model_selection import train_test_split

def build_model2(n_layers =2):
  model = Sequential()
  for i in range(n_layers):
    model.add(Dense(100,activation="relu"))
  model.add(Dense(1,activation="sigmoid"))
  return model

X_train, X_val, y_train, y_cal = train_test_split(data_feature, data_label, test_size=0.2, random_state=42)

layers = [1,2,3,4,5]
for n_layer in layers:
  model = build_model2(n_layer)
  optimizer_to_run = SGD(learning_rate=0.1)
  model.compile(loss="binary_crossentropy", optimizer=optimizer_to_run, metrics=["accuracy"])
  model.fit(X_train,y_train, validation_data=(X_val, y_val), epochs= 100, verbose=None)
  model.save("model_lr"+str(n_layer)+".h5")
  print("Layers: ", n_layer, "Validation Accuracy:", model.evaluate(X_val, y_val, verbose=None))

Layers:  1 Validation Accuracy: [0.8708404302597046, 0.6875]
Layers:  2 Validation Accuracy: [1.314190149307251, 0.625]
Layers:  3 Validation Accuracy: [1.3763139247894287, 0.625]
Layers:  4 Validation Accuracy: [2.110330581665039, 0.5625]
Layers:  5 Validation Accuracy: [2.0450754165649414, 0.625]


**Practice 8: Build a three-layer neural network with softmax function for multi-class classification**

---



In [40]:
# practice 8.1: setup iris dataset for multi-class classification
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()

# get features from iris data
X = iris["data"][:, :] # using all features

# get binary labels for binary classification
y = iris["target"]

print(X.shape)
print(y)

(150, 4)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [41]:
# practice 8.2: Define the neural network classifier with softmax function as output
from keras.models import Sequential
from keras.layers import Dense

model = Sequential() # initialize Sequential model
model.add(Dense(10, input_shape=(X.shape[1],), activation='relu')) # input layer -> hidden layer 1
model.add(Dense(5, activation='relu')) # hidden layer 1 -> hidden layer 2
model.add(Dense(3, activation='softmax')) # hidden layer 2 -> output layer (3 classes, use softmax function to calculate probability)

In [43]:
# Compile model, use categorical_crossentropy as loss function for softmax function
model.compile(loss='categorical_crossentropy',
optimizer='SGD',
metrics=['accuracy'])

In [ ]:
# practice 8.3: Train the model on the training set
model.fit(X, y, validation_split = 0.2, epochs=10)

In [44]:
## re-fit model on the training features and one-hot encoding labels
import tensorflow as tf
y_onehot = tf.keras.utils.to_categorical(y, num_classes=3, dtype='float32')
print(y_onehot)
model.fit(X, y_onehot, validation_split = 0.2, epochs=10)


[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.